spring.sql.init.mode=always
spring.datasource.url=jdbc:postgresql://localhost:5432/studs
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=s336587
spring.datasource.password=5XxvnvSl02KM6ZGD

# ssh -L 5432:pg:5432 s336587@se.ifmo.ru -p 2222
