-- -- Создание ENUM, который отвечает за статус запроса
-- CREATE TYPE request_status AS ENUM ('ACTIVE', 'COMPLETED');
--
-- -- Создание ENUM, который отвечает за статус бронирования
-- CREATE TYPE booking_status AS ENUM ('APPROVED', 'WAITING_FOR_CONFIRMATION', 'REJECTED', 'DONE');
--
-- -- Создание ENUM, который отвечает за статус бронирования
-- CREATE TYPE sex AS ENUM ('MAN', 'WOMAN');

CREATE TABLE IF NOT EXISTS passports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    patronymic VARCHAR(100),
    series VARCHAR(4) NOT NULL,
    number VARCHAR(6) NOT NULL,
    division_code VARCHAR(7) NOT NULL,
    date_of_issue TIMESTAMP NOT NULL,
    issued_by VARCHAR(255) NOT NULL,
    date_of_birth TIMESTAMP NOT NULL,
    sex VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) UNIQUE,
    phone_number VARCHAR(100) UNIQUE,
    passport_id INTEGER UNIQUE REFERENCES passports (id) ON DELETE CASCADE ON UPDATE CASCADE,
    sex VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS passwords (
    user_id INTEGER PRIMARY KEY REFERENCES users (id),
    password VARCHAR(255) NOT NULL
);

-- CREATE TABLE IF NOT EXISTS categories (
--     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     category_name VARCHAR(100) NOT NULL UNIQUE
-- );
--
-- CREATE TABLE IF NOT EXISTS preferences (
--     user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     category_id INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     PRIMARY KEY  (user_id, category_id)
-- );
--
CREATE TABLE IF NOT EXISTS items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    owner_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    status VARCHAR(100) NOT NULL
);
--
-- CREATE TABLE IF NOT EXISTS item_categories (
--     item_id INTEGER NOT NULL REFERENCES items (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     category_id INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     PRIMARY KEY  (item_id, category_id)
-- );
--
-- CREATE TABLE IF NOT EXISTS wishlists (
--     id INTEGER PRIMARY KEY,
--     name VARCHAR(100) NOT NULL,
--     description TEXT NOT NULL,
--     status request_status NOT NULL
-- );
--
-- CREATE TABLE IF NOT EXISTS wishlist_categories (
--     wishlist_id INTEGER NOT NULL REFERENCES wishlists (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     category_id INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     PRIMARY KEY  (wishlist_id, category_id)
-- );
--
-- CREATE TABLE IF NOT EXISTS users_wishlists (
--     user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     wishlist_id INTEGER NOT NULL REFERENCES wishlists (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     PRIMARY KEY  (user_id, wishlist_id)
-- );
--
CREATE TABLE IF NOT EXISTS bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(100) NOT NULL,
    description TEXT
);
--
-- CREATE TABLE IF NOT EXISTS feedbacks (
--     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     title VARCHAR(100) NOT NULL,
--     description TEXT NOT NULL,
--     date TIMESTAMP NOT NULL,
--     rate INTEGER NOT NULL CHECK (rate BETWEEN 0 AND 10)
-- );
--
-- CREATE TABLE IF NOT EXISTS booking_feedbacks (
--     booking_id INTEGER NOT NULL REFERENCES bookings (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     feedback_id INTEGER NOT NULL REFERENCES feedbacks (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     PRIMARY KEY  (booking_id, feedback_id)
-- );
--
CREATE TABLE IF NOT EXISTS booked_items (
    item_id INTEGER NOT NULL REFERENCES items (id) ON DELETE CASCADE ON UPDATE CASCADE,
    booking_id INTEGER NOT NULL REFERENCES bookings (id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY  (item_id, booking_id)
);